### ISSUE TITLE
Preliminary Documentation

### ISSUE THREAD

**Issue by likal** [likal/POLSL_GR1S3_PROJ1#1]

**Comment by likal** [comment]
Documentation will be provided till Wednesday and it will be available only through repository.

**Comment by likal** [comment]
Since Wednesday (11/18/2015) I'll start assigning tasks to each person. Stay tuned

**Comment by likal** [comment]
Please install QT5 Library (version >= 5.4.0) , and QT Creator (ver >=3.3.0 prefered >=3.5.0)

**Comment by likal** [comment]
Please install Visual Studio for Desktop 2013 because QT5 Library has been compiled with _MSC_VER 1800.

Visual Studio Express 2013 with Update 5 for Windows Desktop

https://www.visualstudio.com/downloads/download-visual-studio-vs

Sources will be added today, also new tasks will be assigned to each person, merge my changes should be available by tomorrow. Please be sure that you will be able to compile and run test application which will be added to the repo in seperate directory, we need to be sure that everyone has similar environment.

**Comment by likal** [comment]
Most classes have been ported without implementation due to Unix / Windows differences.

**Comment by likal** [comment]
During work please create a seperate branch with name "Ticket_XXXX" where XXXX is the ticket number (0003), with that approach we can avoid mess, also please keep in mind that ticket worker is responsible to keep the code fresh enough with trunk for easy merge to avoid clash.

**Comment by likal** [comment]
Please try to compile and run Test4 application in Temp directory, if you notice any issues please report them here.

**Comment by procek225** [comment]
I tried to compile Test4 app, and got error:LNK1104: cannot open file 'shell34.lib'.
I'll try to solve that soon. (Why we speak english ? :P)

**Comment by procek225** [comment]
Ok, I've solved that problem: 
![settings](https://cloud.githubusercontent.com/assets/15159325/11404949/156d96da-93a5-11e5-98af-eb536422cec2.png)
![settings2](https://cloud.githubusercontent.com/assets/15159325/11404991/615fe5a2-93a5-11e5-90f3-a8ba202838a3.png)
and some helpfull links: 
http://stackoverflow.com/questions/28105824/qt-fails-to-open-shell32-lib-even-when-included
https://wiki.qt.io/Qt_Creator_Windows_Debugging
